# Generated by Django 3.0.7 on 2020-06-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillup', '0005_myenrolledcourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myenrolledcourses',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='myenrolledcourses',
            name='prev_text',
        ),
    ]
