# Generated by Django 3.0.7 on 2020-06-15 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillup', '0006_auto_20200615_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('vid_url', models.CharField(max_length=65)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skillup.Course')),
            ],
        ),
    ]
