# Generated by Django 3.0.7 on 2020-06-15 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillup', '0007_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='myenrolledcourses',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skillup.Course'),
        ),
    ]
