# Generated by Django 3.0.7 on 2020-06-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillup', '0009_auto_20200615_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('email', models.CharField(max_length=65)),
                ('message', models.TextField()),
            ],
        ),
    ]
